travis:
  secure:
    BINSTAR_TOKEN: K2bt6UHjW3NIhXbuTGXLHyK4ZEPzZDz8k9GkifRKnYAf6c+k3PS6Q5EFvMkHASxXPhAqy6B3F/fJb+CWgqU9vU8+gIP2Du6WiQ31PQmj+GdQWI0vEK3E1y4zhZy2eY2xj+5zh1Ge/2SHFtrR/flQFCUGCOKsa4X1HVVzqdbv1RnY5KWTxqAYZ8wYPwWdCRZb0sPb4Vt8ukEMmgDDnBSQwFHT+JGGawI8i127SIvICNe2q3pbsqfodxRRLNTMCq98B3mec5SzZ7CmoU9q7iao09HvC3dqeDMi8K+o4LqTvfSrAjm172jBQe8Eyg4WyR/OA8Ta7Wfl7Ly1ASS0eEg9kTIMQ0ahhcGegLGVTFplPIw3J1RU/enYQGbmWh9H81M0y78BFWKPhSZ06RAMeoLKnYQH6cqO5fRabTZ/dww0UBURMiz9lqRBih0KZwAfQa9538div6S609uQ3Tr14fQ6cNkqcnWELWSxYKvLYXMWqOdepnTS+EJ7DR8ZVQjPlSrxwGaMi4cFNf0P+tq9u50ML/MPeHriiGL01t+wxukrFz6W6ABfFqBEoElYYQgRQQLYcYa20MsYYQcUgdT+6T27JiiwKN+E/AXNcH4/LbdvqX89iuDeBzZVJI0CgdMMJ6jC88ZuXUVrx+2YAbamEt/J83cUWYMDrezz6aWkml3zNSs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
